//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.07 at 01:56:49 PM GMT+04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.alekseiterentev.ru/shop/ws/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.gb.alekseiterentev.shop.ws.model.products;
